Clarify requirements for push endpoint determinism and predictability
w3c/push-api pull request #274
Opened 2017-06-26 13:24 UTC by beverloo

/cc @magnus-git

2017-06-26 16:15 UTC, martinthomson requested changes
You should reference the text in RFC 8030 about this: https://tools.ietf.org/html/rfc8030#section-8.2

2017-06-26 16:15 UTC, martinthomson commented on index.html
> +        The <a>push endpoint</a> MUST NOT enable information about the user to be derived by actors
s/enable/expose

2017-06-26 16:15 UTC, martinthomson commented on index.html
> +        <a>application server</a> [[!WEBPUSH-VAPID]] MUST NOT generate predictable
Why is this requirement only levied on endpoints that are NOT restricted?  RFC 8030 is pretty clear on this point and restriction to an application server doesn't change that.

2017-08-21 16:56 UTC, beverloo reviewed
Thanks! Please take another look, I've applied the changes and s/WEBPUSH-PROTOCOL/RFC8030/ everywhere. I'll run tidy after the current series of changes landed.

2017-08-21 16:56 UTC, beverloo commented on index.html
> +        The <a>push endpoint</a> MUST NOT enable information about the user to be derived by actors
Done.

2017-08-21 16:56 UTC, beverloo commented on index.html
> +        <a>application server</a> [[!WEBPUSH-VAPID]] MUST NOT generate predictable
Good point - I've updated this to refer 8030 instead.

2017-08-21 22:17 UTC, magnus-git commented
This update looks good to me, thanks!

2017-10-26 22:33 UTC, merged